export const actionTypes = {
    IS_LOADING: 'IS_LOADING',
    HAS_ERROR: 'HAS_ERROR',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILED: 'FETCH_PRODUCTS_FAILED',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAILED: 'FETCH_PRODUCT_FAILED'
};
